/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Report service health and verify DB connectivity with ``SELECT 1``.
     *
     *     Args:
     *         session: Injected async DB session.
     *
     *     Returns:
     *         dict[str, str]: ``{"status": "ok"}`` when the service and DB respond.
     */
    get: operations['health_api_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Categories
     * @description Return the active category tree for the resolved language.
     *
     *     Args:
     *         lang: Resolved request language.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         list[CategoryNode]: Root nodes with nested children.
     */
    get: operations['list_categories_api_v1_catalog_categories_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/categories/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Category
     * @description Return a category with breadcrumbs and subcategories.
     *
     *     Args:
     *         slug: Localized category slug.
     *         lang: Resolved request language.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         CategoryDetail: The category detail response.
     *
     *     Raises:
     *         HTTPException: 404 if the category is not found in the language.
     */
    get: operations['get_category_api_v1_catalog_categories__slug__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/categories/{slug}/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Category Products
     * @description Return a keyset-paginated product listing for a category (§5.3).
     *
     *     Args:
     *         slug: Localized category slug.
     *         sort: Sort order.
     *         cursor: Opaque cursor from a previous page (``None`` = first page).
     *         price_min: Optional inclusive lower price bound.
     *         price_max: Optional inclusive upper price bound.
     *         lang: Resolved request language.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         ProductListing: ``{data, next_cursor}`` envelope.
     *
     *     Raises:
     *         HTTPException: 404 if the category is unknown, 400 for a bad cursor.
     */
    get: operations['list_category_products_api_v1_catalog_categories__slug__products_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/products/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Product
     * @description Return a product detail page (characteristics, media, both slugs).
     *
     *     Args:
     *         slug: Localized product slug.
     *         lang: Resolved request language.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         ProductDetail: The PDP response.
     *
     *     Raises:
     *         HTTPException: 404 if the product is not found / inactive.
     */
    get: operations['get_product_api_v1_catalog_products__slug__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search
     * @description Full-text search over the catalog, ranked and page-paginated (§4).
     *
     *     Args:
     *         q: Full-text query (matched on name/description via the language config,
     *             plus article code).
     *         page: 1-based page number.
     *         page_size: Results per page.
     *         lang: Resolved request language.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         SearchResponse: ``{data, total, page, page_size}`` ordered by relevance.
     */
    get: operations['search_api_v1_search_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/catalog/categories/{slug}/facets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Category Facets
     * @description Return live facets for a category subtree (§6.2).
     *
     *     Args:
     *         slug: Localized category slug.
     *         lang: Resolved request language.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         FacetsResponse: Attribute values + counts + price bounds for the subtree.
     *
     *     Raises:
     *         HTTPException: 404 if the category is unknown in the language.
     */
    get: operations['category_facets_api_v1_catalog_categories__slug__facets_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cart': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Cart
     * @description Return the current cart with prices/totals recomputed live (§2.3).
     *
     *     Args:
     *         request: Incoming request (source of the guest cookie).
     *         user: The authenticated user, or ``None`` for a guest.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         CartOut: The live-priced cart (empty when the caller has no cart).
     */
    get: operations['get_cart_api_v1_cart_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cart/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add Item
     * @description Add a product to the cart (increments ``qty`` if already present, §2.3).
     *
     *     A cookie-less guest is issued a fresh ``session_token`` cookie here.
     *
     *     Args:
     *         data: The product id + quantity to add.
     *         request: Incoming request (guest cookie).
     *         response: Outgoing response (to set the guest cookie).
     *         user: The authenticated user, or ``None`` for a guest.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         CartOut: The re-rendered cart.
     *
     *     Raises:
     *         HTTPException: 404 if the product is missing or inactive.
     */
    post: operations['add_item_api_v1_cart_items_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cart/items/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove Item
     * @description Remove a line from the cart.
     *
     *     Args:
     *         product_id: The product whose line is removed.
     *         request: Incoming request (guest cookie).
     *         user: The authenticated user, or ``None`` for a guest.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         CartOut: The re-rendered cart.
     *
     *     Raises:
     *         HTTPException: 404 if the cart or line does not exist.
     */
    delete: operations['remove_item_api_v1_cart_items__product_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Item
     * @description Set an absolute quantity on an existing cart line.
     *
     *     Args:
     *         product_id: The product whose line is being changed.
     *         data: The new absolute quantity.
     *         request: Incoming request (guest cookie).
     *         user: The authenticated user, or ``None`` for a guest.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         CartOut: The re-rendered cart.
     *
     *     Raises:
     *         HTTPException: 404 if the cart or line does not exist.
     */
    patch: operations['update_item_api_v1_cart_items__product_id__patch'];
    trace?: never;
  };
  '/api/v1/cart/merge': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Merge Cart
     * @description Merge the guest cart (cookie) into the user cart after login (§7).
     *
     *     A no-op when there is no guest cookie / cart. The guest cookie is cleared on
     *     success so the merged-away cart is not re-created.
     *
     *     Args:
     *         request: Incoming request (guest cookie).
     *         response: Outgoing response (to clear the guest cookie).
     *         user: The authenticated user (required).
     *         session: Injected async DB session.
     *
     *     Returns:
     *         CartOut: The re-rendered user cart.
     */
    post: operations['merge_cart_api_v1_cart_merge_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/checkout/quote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Quote
     * @description Return the checkout totals without creating an order (§9, idempotent).
     *
     *     Args:
     *         data: Delivery choice for the predraft.
     *         request: Incoming request (guest cookie).
     *         user: The authenticated user, or ``None`` for a guest.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         QuoteOut: The subtotal / discount / delivery / total breakdown.
     *
     *     Raises:
     *         HTTPException: 400 for an empty cart; 422 for courier without an address.
     */
    post: operations['quote_api_v1_checkout_quote_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/checkout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Checkout
     * @description Create a COD order from the caller's cart atomically (§9.6).
     *
     *     Args:
     *         data: Contact + delivery details for the order.
     *         request: Incoming request (guest cookie).
     *         user: The authenticated user, or ``None`` for a guest order.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         OrderOut | JSONResponse: The created order, or a 409 ``out_of_stock``
     *             envelope when stock is insufficient.
     *
     *     Raises:
     *         HTTPException: 400 empty cart; 422 courier without an address.
     */
    post: operations['checkout_api_v1_checkout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Orders
     * @description Return the authenticated user's orders, newest first (§4).
     *
     *     Args:
     *         user: The authenticated user (required — 401 without a token).
     *         session: Injected async DB session.
     *
     *     Returns:
     *         list[OrderOut]: The user's orders with their lines.
     */
    get: operations['list_orders_api_v1_orders_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders/{number}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Order
     * @description Return one order, authorized by JWT ownership OR guest ``?email=`` (§9).
     *
     *     A logged-in caller may only see their own order. A guest (no/any token) must
     *     supply the matching ``email`` of a guest order. Any authorization miss —
     *     unknown number, not-your-order, wrong/absent email — returns 404 so order
     *     existence is never leaked.
     *
     *     Args:
     *         number: The order number.
     *         email: Contact email (required for guest-order lookup).
     *         user: The authenticated user, or ``None`` for a guest.
     *         session: Injected async DB session.
     *
     *     Returns:
     *         OrderOut: The order with its lines.
     *
     *     Raises:
     *         HTTPException: 404 if the order is absent or not authorized to the caller.
     */
    get: operations['get_order_api_v1_orders__number__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Register a new user (duplicate email/phone -> 409).
     */
    post: operations['register_api_v1_auth_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Authenticate, set auth cookies, and return the token pair.
     */
    post: operations['login_api_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh
     * @description Rotate the refresh token and issue a new pair (revoked/invalid -> 401).
     */
    post: operations['refresh_api_v1_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Blacklist the refresh token and clear auth cookies.
     */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Me
     * @description Return the authenticated user's profile.
     */
    get: operations['get_me_api_v1_users_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Me
     * @description Apply a partial update to the authenticated user's profile.
     */
    patch: operations['update_me_api_v1_users_me_patch'];
    trace?: never;
  };
  '/api/v1/users/me/addresses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Addresses
     * @description List the authenticated user's addresses.
     */
    get: operations['list_addresses_api_v1_users_me_addresses_get'];
    put?: never;
    /**
     * Create Address
     * @description Create a new address (keeps at most one default per user).
     */
    post: operations['create_address_api_v1_users_me_addresses_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me/addresses/{address_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Address
     * @description Delete one of the authenticated user's addresses.
     */
    delete: operations['delete_address_api_v1_users_me_addresses__address_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Address
     * @description Update one of the authenticated user's addresses.
     */
    patch: operations['update_address_api_v1_users_me_addresses__address_id__patch'];
    trace?: never;
  };
  '/api/v1/admin/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Category
     * @description Create a category with its initial translations.
     */
    post: operations['create_category_api_v1_admin_categories_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/categories/{category_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Category
     * @description Delete an empty category (no children / products).
     */
    delete: operations['delete_category_api_v1_admin_categories__category_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Category
     * @description Update a category's structural fields.
     */
    patch: operations['update_category_api_v1_admin_categories__category_id__patch'];
    trace?: never;
  };
  '/api/v1/admin/categories/{category_id}/translations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Set Category Translation
     * @description Upsert one language translation of a category.
     */
    put: operations['set_category_translation_api_v1_admin_categories__category_id__translations_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/categories/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reorder Categories
     * @description Assign new ``position`` values to a set of sibling categories.
     */
    post: operations['reorder_categories_api_v1_admin_categories_reorder_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/categories/{category_id}/move': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Move Category
     * @description Re-parent a category and recompute ``path``/``depth`` for its subtree.
     */
    post: operations['move_category_api_v1_admin_categories__category_id__move_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search Products
     * @description Search back-office products by ``code`` or translated name.
     */
    get: operations['search_products_api_v1_admin_products_get'];
    put?: never;
    /**
     * Create Product
     * @description Create a product with its initial translations.
     */
    post: operations['create_product_api_v1_admin_products_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Product
     * @description Delete a product with its translations, media, attributes and cards.
     */
    delete: operations['delete_product_api_v1_admin_products__product_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Product
     * @description Update a product; activation enforces the both-languages rule (§2.1.1).
     */
    patch: operations['update_product_api_v1_admin_products__product_id__patch'];
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}/translations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Set Product Translation
     * @description Upsert one language translation of a product and rebuild the card.
     */
    put: operations['set_product_translation_api_v1_admin_products__product_id__translations_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}/attributes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Set Product Attributes
     * @description Replace a product's attribute-value links with the given set.
     */
    put: operations['set_product_attributes_api_v1_admin_products__product_id__attributes_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}/media': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload Product Media
     * @description Store an uploaded image and record its :class:`Media` row.
     */
    post: operations['upload_product_media_api_v1_admin_products__product_id__media_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/attributes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Attribute
     * @description Create an attribute dictionary entry with its translations.
     */
    post: operations['create_attribute_api_v1_admin_attributes_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/attributes/{attribute_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Attribute
     * @description Delete an attribute with its translations, values and links.
     */
    delete: operations['delete_attribute_api_v1_admin_attributes__attribute_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Attribute
     * @description Update an attribute's ``code`` and/or its translations.
     */
    patch: operations['update_attribute_api_v1_admin_attributes__attribute_id__patch'];
    trace?: never;
  };
  '/api/v1/admin/attributes/{attribute_id}/values': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Attribute Value
     * @description Create a value under an attribute with its translations.
     */
    post: operations['create_attribute_value_api_v1_admin_attributes__attribute_id__values_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/attributes/values/{value_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Attribute Value
     * @description Delete an attribute value, its translations and product links.
     */
    delete: operations['delete_attribute_value_api_v1_admin_attributes_values__value_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Attribute Value
     * @description Replace an attribute value's translations.
     */
    patch: operations['update_attribute_value_api_v1_admin_attributes_values__value_id__patch'];
    trace?: never;
  };
  '/api/v1/admin/orders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Orders
     * @description Return a filtered, paginated page of orders for the back office (§10).
     *
     *     Args:
     *         status: Optional exact fulfilment-status filter.
     *         q: Optional free-text search over number / email / phone.
     *         page: 1-based page number.
     *         page_size: Items per page.
     *         _staff: The authenticated staff user (guards the endpoint).
     *         session: Injected async DB session.
     *
     *     Returns:
     *         AdminOrderList: The ``{data, total, page, page_size}`` envelope.
     */
    get: operations['list_orders_api_v1_admin_orders_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/orders/{number}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Order
     * @description Return one order with its lines by number (§10).
     *
     *     Args:
     *         number: The order number.
     *         _staff: The authenticated staff user (guards the endpoint).
     *         session: Injected async DB session.
     *
     *     Returns:
     *         OrderOut: The order with its lines.
     *
     *     Raises:
     *         HTTPException: 404 if no order has that number.
     */
    get: operations['get_order_api_v1_admin_orders__number__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/orders/{number}/transition': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Transition Order
     * @description Apply a status/payment transition to an order via the shared machine (§8).
     *
     *     Reuses the storefront ``OrderService.transition`` — the same state machine and
     *     the same history-writing path — so admin and storefront never diverge. An
     *     illegal move is rejected with a 409 domain error.
     *
     *     Args:
     *         number: The order number to transition.
     *         data: The requested status and/or payment move.
     *         staff: The authenticated staff user (recorded as the actor).
     *         session: Injected async DB session.
     *
     *     Returns:
     *         OrderOut: The updated order with its lines.
     *
     *     Raises:
     *         HTTPException: 404 if the order is unknown; 409 for an illegal move.
     */
    post: operations['transition_order_api_v1_admin_orders__number__transition_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AddItem
     * @description Request body for ``POST /cart/items`` — add or increment a product.
     */
    AddItem: {
      /**
       * Product Id
       * @description Catalog product id to add.
       */
      product_id: number;
      /**
       * Qty
       * @description Quantity to add (increments if present).
       */
      qty: number;
    };
    /**
     * AddressCreate
     * @description Payload to create an address (``POST /users/me/addresses``).
     */
    AddressCreate: {
      /** Full Name */
      full_name: string;
      /** Phone */
      phone: string;
      /** City */
      city: string;
      /** Street */
      street: string;
      /** Zip */
      zip?: string | null;
      /**
       * Is Default
       * @default false
       */
      is_default: boolean;
    };
    /**
     * AddressOut
     * @description Address response view.
     */
    AddressOut: {
      /** Id */
      id: number;
      /** Full Name */
      full_name: string;
      /** Phone */
      phone: string;
      /** City */
      city: string;
      /** Street */
      street: string;
      /** Zip */
      zip?: string | null;
      /** Is Default */
      is_default: boolean;
    };
    /**
     * AddressUpdate
     * @description Partial address update (``PATCH /users/me/addresses/{id}``).
     */
    AddressUpdate: {
      /** Full Name */
      full_name?: string | null;
      /** Phone */
      phone?: string | null;
      /** City */
      city?: string | null;
      /** Street */
      street?: string | null;
      /** Zip */
      zip?: string | null;
      /** Is Default */
      is_default?: boolean | null;
    };
    /**
     * AttributeCreate
     * @description Create an attribute dictionary entry with its translations.
     */
    AttributeCreate: {
      /** Code */
      code: string;
      /** Translations */
      translations?: components['schemas']['AttributeTranslationIn'][];
    };
    /**
     * AttributeGroup
     * @description Grouped characteristic: one attribute and its resolved value(s) for the PDP.
     */
    AttributeGroup: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Values */
      values?: string[];
    };
    /**
     * AttributeOut
     * @description Full admin view of an attribute (code + translations + values).
     */
    AttributeOut: {
      /** Id */
      id: number;
      /** Code */
      code: string;
      /** Translations */
      translations?: components['schemas']['AttributeTranslationOut'][];
      /** Values */
      values?: components['schemas']['AttributeValueOut'][];
    };
    /**
     * AttributeTranslationIn
     * @description Per-language display name for an attribute.
     */
    AttributeTranslationIn: {
      /** Lang */
      lang: string;
      /** Name */
      name: string;
    };
    /**
     * AttributeTranslationOut
     * @description An attribute translation as returned to the back-office.
     */
    AttributeTranslationOut: {
      /** Lang */
      lang: string;
      /** Name */
      name: string;
    };
    /**
     * AttributeUpdate
     * @description Partial update of an attribute (code and/or translations).
     */
    AttributeUpdate: {
      /** Code */
      code?: string | null;
      /** Translations */
      translations?: components['schemas']['AttributeTranslationIn'][] | null;
    };
    /**
     * AttributeValueCreate
     * @description Create a concrete value under an attribute, with its translations.
     */
    AttributeValueCreate: {
      /** Translations */
      translations?: components['schemas']['AttributeValueTranslationIn'][];
    };
    /**
     * AttributeValueOut
     * @description An attribute value with its translations.
     */
    AttributeValueOut: {
      /** Id */
      id: number;
      /** Attribute Id */
      attribute_id: number;
      /** Translations */
      translations?: components['schemas']['AttributeValueTranslationOut'][];
    };
    /**
     * AttributeValueTranslationIn
     * @description Per-language display text for an attribute value.
     */
    AttributeValueTranslationIn: {
      /** Lang */
      lang: string;
      /** Value */
      value: string;
    };
    /**
     * AttributeValueTranslationOut
     * @description An attribute-value translation as returned to the back-office.
     */
    AttributeValueTranslationOut: {
      /** Lang */
      lang: string;
      /** Value */
      value: string;
    };
    /**
     * AttributeValueUpdate
     * @description Partial update of an attribute value's translations.
     */
    AttributeValueUpdate: {
      /** Translations */
      translations?:
        components['schemas']['AttributeValueTranslationIn'][] | null;
    };
    /** Body_upload_product_media_api_v1_admin_products__product_id__media_post */
    Body_upload_product_media_api_v1_admin_products__product_id__media_post: {
      /** File */
      file: string;
    };
    /**
     * Breadcrumb
     * @description A single breadcrumb entry (root..self order), built from ``category.path``.
     */
    Breadcrumb: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /**
     * CartItemOut
     * @description One cart line with its live price snapshot and computed line total (§2.3).
     */
    CartItemOut: {
      /** Product Id */
      product_id: number;
      /** Name */
      name: string;
      /** Price */
      price: string;
      /** Qty */
      qty: number;
      /** Line Total */
      line_total: string;
    };
    /**
     * CartOut
     * @description The whole cart: live-priced lines plus computed totals (§2.3).
     */
    CartOut: {
      /** Items */
      items?: components['schemas']['CartItemOut'][];
      /** Subtotal */
      subtotal: string;
      /** Item Count */
      item_count: number;
    };
    /**
     * CategoryCreate
     * @description Create a category with its initial translations (root..self path derived).
     */
    CategoryCreate: {
      /** Parent Id */
      parent_id?: number | null;
      /**
       * Position
       * @default 0
       */
      position: number;
      /**
       * Is Active
       * @default false
       */
      is_active: boolean;
      /** Translations */
      translations?: components['schemas']['CategoryTranslationIn'][];
    };
    /**
     * CategoryDetail
     * @description Category detail: localized name/slug + breadcrumbs + children + seo (§4).
     */
    CategoryDetail: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Seo Title */
      seo_title?: string | null;
      /** Seo Description */
      seo_description?: string | null;
      /** Breadcrumbs */
      breadcrumbs?: components['schemas']['Breadcrumb'][];
      /** Children */
      children?: components['schemas']['CategoryNode'][];
    };
    /**
     * CategoryMoveRequest
     * @description Move a category under a new parent (or to root when ``parent_id`` is null).
     */
    CategoryMoveRequest: {
      /** Parent Id */
      parent_id?: number | null;
    };
    /**
     * CategoryNode
     * @description A node in the category tree (navigation).
     */
    CategoryNode: {
      /** Id */
      id: number;
      /** Parent Id */
      parent_id: number | null;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Depth */
      depth: number;
      /** Position */
      position: number;
      /** Children */
      children?: components['schemas']['CategoryNode'][];
    };
    /**
     * CategoryOut
     * @description Full admin view of a category (structure + translations).
     */
    CategoryOut: {
      /** Id */
      id: number;
      /** Parent Id */
      parent_id: number | null;
      /** Path */
      path: number[];
      /** Depth */
      depth: number;
      /** Position */
      position: number;
      /** Is Active */
      is_active: boolean;
      /** Translations */
      translations?: components['schemas']['CategoryTranslationOut'][];
    };
    /**
     * CategoryReorderItem
     * @description One ``(category_id, position)`` assignment in a reorder request.
     */
    CategoryReorderItem: {
      /** Category Id */
      category_id: number;
      /** Position */
      position: number;
    };
    /**
     * CategoryReorderRequest
     * @description Bulk position update for a set of sibling categories.
     */
    CategoryReorderRequest: {
      /** Items */
      items: components['schemas']['CategoryReorderItem'][];
    };
    /**
     * CategoryTranslationIn
     * @description A single per-language translation payload for a category (§2.1.1).
     */
    CategoryTranslationIn: {
      /** Lang */
      lang: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Seo Title */
      seo_title?: string | null;
      /** Seo Description */
      seo_description?: string | null;
    };
    /**
     * CategoryTranslationOut
     * @description A category translation as returned to the back-office.
     */
    CategoryTranslationOut: {
      /** Lang */
      lang: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Seo Title */
      seo_title?: string | null;
      /** Seo Description */
      seo_description?: string | null;
    };
    /**
     * CategoryUpdate
     * @description Partial update of a category's structural fields (translations excluded).
     */
    CategoryUpdate: {
      /** Parent Id */
      parent_id?: number | null;
      /** Position */
      position?: number | null;
      /** Is Active */
      is_active?: boolean | null;
    };
    /**
     * CheckoutRequest
     * @description Request body for ``POST /checkout`` — creates the order (§9).
     *
     *     ``email`` + ``phone`` are always required (guest checkout is allowed, §9); an
     *     authenticated caller's ``user_id`` is taken from the token, not the body.
     */
    CheckoutRequest: {
      /**
       * Email
       * @description Contact email (guest + user).
       */
      email: string;
      /**
       * Phone
       * @description Contact phone (guest + user).
       */
      phone: string;
      /**
       * Delivery Type
       * @description Delivery method (pickup | courier).
       */
      delivery_type: string;
      /**
       * Delivery Address Id
       * @description Delivery address id (required for courier).
       */
      delivery_address_id?: number | null;
    };
    /**
     * FacetAttribute
     * @description One attribute with its localized name and available values (+counts).
     */
    FacetAttribute: {
      /** Attribute Id */
      attribute_id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Values */
      values?: components['schemas']['FacetValue'][];
    };
    /**
     * FacetValue
     * @description One selectable attribute value with its product count in the subtree.
     */
    FacetValue: {
      /** Value Id */
      value_id: number;
      /** Value */
      value: string;
      /** Count */
      count: number;
    };
    /**
     * FacetsResponse
     * @description Live facets for a category subtree (§6.2).
     *
     *     Attributes:
     *         attributes: Attribute facets (values + counts) available in the subtree.
     *         price_min: Lowest active-product price in the subtree (``None`` if empty).
     *         price_max: Highest active-product price in the subtree (``None`` if empty).
     */
    FacetsResponse: {
      /** Attributes */
      attributes?: components['schemas']['FacetAttribute'][];
      /** Price Min */
      price_min?: string | null;
      /** Price Max */
      price_max?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * LoginRequest
     * @description Payload for ``POST /auth/login`` — login by email OR phone.
     *
     *     Exactly one of ``email`` / ``phone`` must be supplied together with the
     *     password.
     */
    LoginRequest: {
      /** Email */
      email?: string | null;
      /** Phone */
      phone?: string | null;
      /** Password */
      password: string;
    };
    /**
     * MediaAdminOut
     * @description A stored product image row (v1: one url per row, no derivatives — §2.1).
     */
    MediaAdminOut: {
      /** Id */
      id: number;
      /** Product Id */
      product_id: number;
      /** Url */
      url: string;
      /** Kind */
      kind: string;
      /** Position */
      position: number;
    };
    /**
     * MediaOut
     * @description A single product image (v1: one url per row, no derivatives — §2.1).
     */
    MediaOut: {
      /** Id */
      id: number;
      /** Url */
      url: string;
      /** Kind */
      kind: string;
      /** Position */
      position: number;
    };
    /**
     * OrderItemOut
     * @description One persisted order line with its name/price snapshot (§2.4).
     */
    OrderItemOut: {
      /** Product Id */
      product_id: number | null;
      /** Name Snapshot */
      name_snapshot: string;
      /** Price Snapshot */
      price_snapshot: string;
      /** Qty */
      qty: number;
    };
    /**
     * OrderOut
     * @description A persisted order with its snapshotted lines (§2.4 / §4).
     */
    OrderOut: {
      /** Number */
      number: string;
      /** Status */
      status: string;
      /** Payment Status */
      payment_status: string;
      /** Email */
      email: string;
      /** Phone */
      phone: string;
      /** Subtotal */
      subtotal: string;
      /** Discount Total */
      discount_total: string;
      /** Delivery Cost */
      delivery_cost: string;
      /** Total */
      total: string;
      /** Delivery Type */
      delivery_type: string;
      /** Delivery Address Id */
      delivery_address_id: number | null;
      /** Payment Method */
      payment_method: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Items */
      items?: components['schemas']['OrderItemOut'][];
    };
    /** Page[OrderOut] */
    Page_OrderOut_: {
      /** Data */
      data: components['schemas']['OrderOut'][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
    };
    /**
     * ProductAttributeSetRequest
     * @description Replace a product's attribute-value links with the given set.
     */
    ProductAttributeSetRequest: {
      /** Value Ids */
      value_ids?: number[];
    };
    /**
     * ProductCardOut
     * @description Listing card, projected from the denormalized ``product_card`` (§5.2).
     */
    ProductCardOut: {
      /** Product Id */
      product_id: number;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Price */
      price: string;
      /** Old Price */
      old_price?: string | null;
      /** In Stock */
      in_stock: boolean;
      /** Main Image Url */
      main_image_url?: string | null;
      /** Badge */
      badge?: string | null;
    };
    /**
     * ProductCreate
     * @description Create a product with its initial translations (inactive by default).
     */
    ProductCreate: {
      /** Category Id */
      category_id: number;
      /** Code */
      code: string;
      /** Price */
      price: number | string;
      /** Old Price */
      old_price?: number | string | null;
      /**
       * Qty
       * @default 0
       */
      qty: number;
      /**
       * Is Active
       * @default false
       */
      is_active: boolean;
      /** Translations */
      translations?: components['schemas']['ProductTranslationIn'][];
    };
    /**
     * ProductDetail
     * @description Product detail page (PDP): product + grouped attributes + media + slugs.
     */
    ProductDetail: {
      /** Id */
      id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Description */
      description?: string | null;
      /** Seo Title */
      seo_title?: string | null;
      /** Seo Description */
      seo_description?: string | null;
      /** Price */
      price: string;
      /** Old Price */
      old_price?: string | null;
      /** In Stock */
      in_stock: boolean;
      /** Category Id */
      category_id: number;
      /** Breadcrumbs */
      breadcrumbs?: components['schemas']['Breadcrumb'][];
      /** Attributes */
      attributes?: components['schemas']['AttributeGroup'][];
      /** Media */
      media?: components['schemas']['MediaOut'][];
      /** Slugs */
      slugs?: components['schemas']['ProductSlug'][];
    };
    /**
     * ProductListing
     * @description Cursor-paginated listing envelope: ``{data, next_cursor}`` (§5.3).
     *
     *     ``next_cursor`` is an opaque token to pass back as ``?cursor=``; ``None``
     *     means the last page has been reached.
     */
    ProductListing: {
      /** Data */
      data: components['schemas']['ProductCardOut'][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /**
     * ProductOut
     * @description Full admin view of a product (structure + translations + media).
     */
    ProductOut: {
      /** Id */
      id: number;
      /** Category Id */
      category_id: number;
      /** Code */
      code: string;
      /** Price */
      price: string;
      /** Old Price */
      old_price?: string | null;
      /** Qty */
      qty: number;
      /** Is Active */
      is_active: boolean;
      /** Translations */
      translations?: components['schemas']['ProductTranslationOut'][];
      /** Media */
      media?: components['schemas']['MediaAdminOut'][];
      /** Value Ids */
      value_ids?: number[];
    };
    /**
     * ProductSearchItem
     * @description A compact product row for the back-office search list.
     */
    ProductSearchItem: {
      /** Id */
      id: number;
      /** Code */
      code: string;
      /** Price */
      price: string;
      /** Is Active */
      is_active: boolean;
      /** Name */
      name?: string | null;
    };
    /**
     * ProductSearchResult
     * @description Envelope for a back-office product search response.
     */
    ProductSearchResult: {
      /** Data */
      data?: components['schemas']['ProductSearchItem'][];
    };
    /**
     * ProductSlug
     * @description A ``(lang, slug)`` pair powering the on-page language switcher (§2.1.1).
     */
    ProductSlug: {
      /** Lang */
      lang: string;
      /** Slug */
      slug: string;
    };
    /**
     * ProductSort
     * @description Allowed sort orders for the category listing (§4).
     * @enum {string}
     */
    ProductSort: 'newest' | 'price_asc' | 'price_desc';
    /**
     * ProductTranslationIn
     * @description A single per-language translation payload for a product (§2.1.1).
     */
    ProductTranslationIn: {
      /** Lang */
      lang: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Description */
      description?: string | null;
      /** Seo Title */
      seo_title?: string | null;
      /** Seo Description */
      seo_description?: string | null;
    };
    /**
     * ProductTranslationOut
     * @description A product translation as returned to the back-office.
     */
    ProductTranslationOut: {
      /** Lang */
      lang: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Description */
      description?: string | null;
      /** Seo Title */
      seo_title?: string | null;
      /** Seo Description */
      seo_description?: string | null;
    };
    /**
     * ProductUpdate
     * @description Partial update of a product's structural / price / stock fields.
     *
     *     Setting ``is_active=True`` enforces the both-languages publication rule
     *     (§2.1.1) in the service before the card read-model is rebuilt.
     */
    ProductUpdate: {
      /** Category Id */
      category_id?: number | null;
      /** Code */
      code?: string | null;
      /** Price */
      price?: number | string | null;
      /** Old Price */
      old_price?: number | string | null;
      /** Qty */
      qty?: number | null;
      /** Is Active */
      is_active?: boolean | null;
    };
    /**
     * QuoteOut
     * @description Computed checkout totals returned by ``POST /checkout/quote`` (§9).
     */
    QuoteOut: {
      /** Subtotal */
      subtotal: string;
      /** Discount Total */
      discount_total: string;
      /** Delivery Cost */
      delivery_cost: string;
      /** Total */
      total: string;
      /** Delivery Type */
      delivery_type: string;
      /** Item Count */
      item_count: number;
    };
    /**
     * QuoteRequest
     * @description Request body for ``POST /checkout/quote`` — a pure predraft (§9).
     */
    QuoteRequest: {
      /**
       * Delivery Type
       * @description Delivery method (pickup | courier).
       */
      delivery_type: string;
      /**
       * Delivery Address Id
       * @description Delivery address id (required for courier).
       */
      delivery_address_id?: number | null;
    };
    /**
     * RefreshRequest
     * @description Payload for ``POST /auth/refresh``.
     *
     *     The refresh token may also arrive via the ``refresh`` cookie; this body form
     *     is the fallback when the cookie is absent.
     */
    RefreshRequest: {
      /** Refresh */
      refresh?: string | null;
    };
    /**
     * RegisterRequest
     * @description Payload for ``POST /auth/register``.
     */
    RegisterRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
      /** Phone */
      phone?: string | null;
    };
    /**
     * SearchHit
     * @description A single search result: a listing card plus its relevance rank.
     *
     *     ``rank`` combines the FTS ``ts_rank`` with the article-code boost; higher is
     *     more relevant. It is exposed for debugging/observability, not for display.
     */
    SearchHit: {
      card: components['schemas']['ProductCardOut'];
      /** Rank */
      rank: number;
    };
    /**
     * SearchResponse
     * @description Page-paginated, relevance-ranked search envelope (§4).
     *
     *     Uses classic ``{data, total, page, page_size}`` pagination (not keyset): FTS
     *     relevance order is not a stable monotonic key, so keyset cursors do not apply
     *     here. ``data`` is ordered by descending relevance.
     */
    SearchResponse: {
      /** Data */
      data?: components['schemas']['SearchHit'][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
    };
    /**
     * TokenPair
     * @description Access + refresh token pair returned by login/refresh.
     */
    TokenPair: {
      /** Access */
      access: string;
      /** Refresh */
      refresh: string;
    };
    /**
     * TransitionRequest
     * @description Body for ``POST /admin/orders/{number}/transition`` (§8 / §10).
     *
     *     At least one axis must be supplied. Each axis is validated by the shared
     *     :class:`~app.services.order_service.OrderService` state machine — an illegal
     *     move raises a domain error rather than silently mutating the order.
     */
    TransitionRequest: {
      /**
       * To Status
       * @description Target fulfilment status (new | confirmed | done | canceled).
       */
      to_status?: string | null;
      /**
       * To Payment Status
       * @description Target payment status (pending | paid | refunded).
       */
      to_payment_status?: string | null;
    };
    /**
     * UpdateItem
     * @description Request body for ``PATCH /cart/items/{product_id}`` — set an absolute qty.
     */
    UpdateItem: {
      /**
       * Qty
       * @description New absolute quantity for the line.
       */
      qty: number;
    };
    /**
     * UserMe
     * @description Current-user profile view (``GET /users/me``).
     */
    UserMe: {
      /** Id */
      id: number;
      /** Email */
      email: string;
      /** Phone */
      phone?: string | null;
      /** Is Active */
      is_active: boolean;
      /** Is Staff */
      is_staff: boolean;
    };
    /**
     * UserUpdate
     * @description Partial profile update (``PATCH /users/me``).
     */
    UserUpdate: {
      /** Phone */
      phone?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_categories_api_v1_catalog_categories_get: {
    parameters: {
      query?: {
        /** @description Language code (ru|ro). */
        lang?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryNode'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_category_api_v1_catalog_categories__slug__get: {
    parameters: {
      query?: {
        /** @description Language code (ru|ro). */
        lang?: string | null;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_category_products_api_v1_catalog_categories__slug__products_get: {
    parameters: {
      query?: {
        sort?: components['schemas']['ProductSort'];
        cursor?: string | null;
        price_min?: number | string | null;
        price_max?: number | string | null;
        value_ids?: number[] | null;
        /** @description Language code (ru|ro). */
        lang?: string | null;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductListing'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_product_api_v1_catalog_products__slug__get: {
    parameters: {
      query?: {
        /** @description Language code (ru|ro). */
        lang?: string | null;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  search_api_v1_search_get: {
    parameters: {
      query: {
        /** @description Full-text search query. */
        q: string;
        /** @description 1-based page number. */
        page?: number;
        /** @description Results per page. */
        page_size?: number;
        /** @description Language code (ru|ro). */
        lang?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  category_facets_api_v1_catalog_categories__slug__facets_get: {
    parameters: {
      query?: {
        /** @description Language code (ru|ro). */
        lang?: string | null;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FacetsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_cart_api_v1_cart_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
    };
  };
  add_item_api_v1_cart_items_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddItem'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_item_api_v1_cart_items__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_item_api_v1_cart_items__product_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateItem'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  merge_cart_api_v1_cart_merge_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
    };
  };
  quote_api_v1_checkout_quote_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QuoteRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuoteOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  checkout_api_v1_checkout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CheckoutRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrderOut'];
        };
      };
      /** @description Insufficient stock */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_orders_api_v1_orders_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrderOut'][];
        };
      };
    };
  };
  get_order_api_v1_orders__number__get: {
    parameters: {
      query?: {
        email?: string | null;
      };
      header?: never;
      path: {
        number: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrderOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserMe'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPair'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['RefreshRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPair'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['RefreshRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_me_api_v1_users_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserMe'];
        };
      };
    };
  };
  update_me_api_v1_users_me_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserMe'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_addresses_api_v1_users_me_addresses_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AddressOut'][];
        };
      };
    };
  };
  create_address_api_v1_users_me_addresses_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddressCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AddressOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_address_api_v1_users_me_addresses__address_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_address_api_v1_users_me_addresses__address_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddressUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AddressOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_category_api_v1_admin_categories_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_category_api_v1_admin_categories__category_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_category_api_v1_admin_categories__category_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  set_category_translation_api_v1_admin_categories__category_id__translations_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryTranslationIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryTranslationOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reorder_categories_api_v1_admin_categories_reorder_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryReorderRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  move_category_api_v1_admin_categories__category_id__move_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryMoveRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  search_products_api_v1_admin_products_get: {
    parameters: {
      query?: {
        search?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductSearchResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_product_api_v1_admin_products_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_product_api_v1_admin_products__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_product_api_v1_admin_products__product_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  set_product_translation_api_v1_admin_products__product_id__translations_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductTranslationIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductTranslationOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  set_product_attributes_api_v1_admin_products__product_id__attributes_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductAttributeSetRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_product_media_api_v1_admin_products__product_id__media_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_product_media_api_v1_admin_products__product_id__media_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MediaAdminOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_attribute_api_v1_admin_attributes_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AttributeCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AttributeOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_attribute_api_v1_admin_attributes__attribute_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attribute_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_attribute_api_v1_admin_attributes__attribute_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attribute_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AttributeUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AttributeOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_attribute_value_api_v1_admin_attributes__attribute_id__values_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attribute_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AttributeValueCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AttributeValueOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_attribute_value_api_v1_admin_attributes_values__value_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        value_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_attribute_value_api_v1_admin_attributes_values__value_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        value_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AttributeValueUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AttributeValueOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_orders_api_v1_admin_orders_get: {
    parameters: {
      query?: {
        /** @description Exact fulfilment status filter. */
        status?: string | null;
        /** @description Search over number / email / phone. */
        q?: string | null;
        /** @description 1-based page number. */
        page?: number;
        /** @description Items per page. */
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_OrderOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_order_api_v1_admin_orders__number__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        number: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrderOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  transition_order_api_v1_admin_orders__number__transition_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        number: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrderOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
